
--region [dbo].[usp_InsertSalary_Component_Name]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   giang using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertSalary_Component_Name]
-- Date Generated: Wednesday, September 16, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertSalary_Component_Name]
	@Salary_Component nvarchar(100),
	@Name_VN nvarchar(100),
	@Name_EN nvarchar(100),
	@Name_KR nvarchar(100)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Salary_Component_Name] (
	[Salary_Component],
	[Name_VN],
	[Name_EN],
	[Name_KR]
) VALUES (
	@Salary_Component,
	@Name_VN,
	@Name_EN,
	@Name_KR
)

--endregion





GO
