
--region [dbo].[usp_InsertSmartBooks_Salary_Name]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertSmartBooks_Salary_Name]
-- Date Generated: 07 July 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertSmartBooks_Salary_Name]
	@Salary nvarchar(100),
	@Name_VN nvarchar(100),
	@Name_EN nvarchar(100),
	@Name_KR nvarchar(100)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[SmartBooks_Salary_Name] (
	[Salary],
	[Name_VN],
	[Name_EN],
	[Name_KR]
) VALUES (
	@Salary,
	@Name_VN,
	@Name_EN,
	@Name_KR
)

--endregion





GO
