
--region [dbo].[usp_InsertHR_TemplateReport]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   giang using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertHR_TemplateReport]
-- Date Generated: Monday, August 24, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertHR_TemplateReport]
	@ID varchar(100),
	@FileTemp nvarchar(100),
	@ColExel nvarchar(100),
	@ColOrCell bit,
	@Comment nvarchar(500),
	@KeyCol nvarchar(50),
	@UpOrDown bit,
	@ViewOnSalaryTable nvarchar(50)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[HR_TemplateReport] (
	[ID],
	[FileTemp],
	[ColExel],
	[ColOrCell],
	[Comment],
	[KeyCol],
	[UpOrDown],
	[ViewOnSalaryTable]
) VALUES (
	@ID,
	@FileTemp,
	@ColExel,
	@ColOrCell,
	@Comment,
	@KeyCol,
	@UpOrDown,
	@ViewOnSalaryTable
)

--endregion





GO
