

--region [dbo].[usp_SelectSetUpsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectSetUpsAll]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectSetUpsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[Value],
	[Comment_VN],
	[Comment_EN],
	[FunctionID]
FROM
	[dbo].[SetUp]

--endregion






GO
