

--region [dbo].[usp_SelectSetUp]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectSetUp]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectSetUp]
	@ID nvarchar(255)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[Value],
	[Comment_VN],
	[Comment_EN],
	[FunctionID]
FROM
	[dbo].[SetUp]
WHERE
	[ID] = @ID

--endregion






GO
