

--region [dbo].[usp_UpdateSetUp]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateSetUp]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateSetUp]
	@ID nvarchar(255),
	@Value nvarchar(255),
	@Comment_VN nvarchar(255),
	@Comment_EN nvarchar(255),
	@FunctionID nvarchar(255)
AS

SET NOCOUNT ON

UPDATE [dbo].[SetUp] SET
	[Value] = @Value,
	[Comment_VN] = @Comment_VN,
	[Comment_EN] = @Comment_EN,
	[FunctionID] = @FunctionID
WHERE
	[ID] = @ID

--endregion






GO
