

--region [dbo].[usp_InsertUpdateSetUp]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateSetUp]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateSetUp]
	@ID nvarchar(255),
	@Value nvarchar(255),
	@Comment_VN nvarchar(255),
	@Comment_EN nvarchar(255),
	@FunctionID nvarchar(255)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [ID] FROM [dbo].[SetUp] WHERE [ID] = @ID)
BEGIN
	UPDATE [dbo].[SetUp] SET
		[Value] = @Value,
		[Comment_VN] = @Comment_VN,
		[Comment_EN] = @Comment_EN,
		[FunctionID] = @FunctionID
	WHERE
		[ID] = @ID
END
ELSE
BEGIN
	INSERT INTO [dbo].[SetUp] (
		[ID],
		[Value],
		[Comment_VN],
		[Comment_EN],
		[FunctionID]
	) VALUES (
		@ID,
		@Value,
		@Comment_VN,
		@Comment_EN,
		@FunctionID
	)
END

--endregion






GO
