
--region [dbo].[usp_InsertUpdateSmartBooks_Salary_Name]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateSmartBooks_Salary_Name]
-- Date Generated: 07 July 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateSmartBooks_Salary_Name]
	@Salary nvarchar(100),
	@Name_VN nvarchar(100),
	@Name_EN nvarchar(100),
	@Name_KR nvarchar(100)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Salary] FROM [dbo].[SmartBooks_Salary_Name] WHERE [Salary] = @Salary)
BEGIN
	UPDATE [dbo].[SmartBooks_Salary_Name] SET
		[Name_VN] = @Name_VN,
		[Name_EN] = @Name_EN,
		[Name_KR] = @Name_KR
	WHERE
		[Salary] = @Salary
END
ELSE
BEGIN
	INSERT INTO [dbo].[SmartBooks_Salary_Name] (
		[Salary],
		[Name_VN],
		[Name_EN],
		[Name_KR]
	) VALUES (
		@Salary,
		@Name_VN,
		@Name_EN,
		@Name_KR
	)
END

--endregion





GO
