
--region [dbo].[usp_UpdateHR_DayVacationRemain]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateHR_DayVacationRemain]
-- Date Generated: 09 July 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateHR_DayVacationRemain]
	@Year int,
	@Employee_ID nvarchar(50),
	@DaysRemain float,
	@DaysPayment float,
	@TotalDays float,
	@InsertBy nvarchar(50),
	@InsertDate datetime,
	@UpdateBy nvarchar(50),
	@updateDate datetime
AS

SET NOCOUNT ON

UPDATE [dbo].[HR_DayVacationRemain] SET
	[DaysRemain] = @DaysRemain,
	[DaysPayment] = @DaysPayment,
	[TotalDays] = @TotalDays,
	[InsertBy] = @InsertBy,
	[InsertDate] = @InsertDate,
	[UpdateBy] = @UpdateBy,
	[updateDate] = @updateDate
WHERE
	[Year] = @Year
	AND [Employee_ID] = @Employee_ID

--endregion





GO
