
--region [dbo].[usp_DeleteUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   giang using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteUser]
-- Date Generated: Monday, August 17, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteUser]
	@UserName varchar(50)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[User]
WHERE
	[UserName] = @UserName

--endregion





GO
