
--region [dbo].[usp_UpdateHR_TemplateReport]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   giang using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateHR_TemplateReport]
-- Date Generated: Monday, August 24, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateHR_TemplateReport]
	@ID varchar(100),
	@FileTemp nvarchar(100),
	@ColExel nvarchar(100),
	@ColOrCell bit,
	@Comment nvarchar(500),
	@KeyCol nvarchar(50),
	@UpOrDown bit,
	@ViewOnSalaryTable nvarchar(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[HR_TemplateReport] SET
	[ColOrCell] = @ColOrCell,
	[Comment] = @Comment,
	[KeyCol] = @KeyCol,
	[UpOrDown] = @UpOrDown,
	[ViewOnSalaryTable] = @ViewOnSalaryTable
WHERE
	[ID] = @ID
	AND [FileTemp] = @FileTemp
	AND [ColExel] = @ColExel

--endregion





GO
