

--region [dbo].[usp_InsertSetUp]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertSetUp]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertSetUp]
	@ID nvarchar(255),
	@Value nvarchar(255),
	@Comment_VN nvarchar(255),
	@Comment_EN nvarchar(255),
	@FunctionID nvarchar(255)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[SetUp] (
	[ID],
	[Value],
	[Comment_VN],
	[Comment_EN],
	[FunctionID]
) VALUES (
	@ID,
	@Value,
	@Comment_VN,
	@Comment_EN,
	@FunctionID
)

--endregion






GO
