
--region [dbo].[usp_InsertHR_DayVacationRemain]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertHR_DayVacationRemain]
-- Date Generated: 09 July 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertHR_DayVacationRemain]
	@Year int,
	@Employee_ID nvarchar(50),
	@DaysRemain float,
	@DaysPayment float,
	@TotalDays float,
	@InsertBy nvarchar(50),
	@InsertDate datetime,
	@UpdateBy nvarchar(50),
	@updateDate datetime
AS

SET NOCOUNT ON

INSERT INTO [dbo].[HR_DayVacationRemain] (
	[Year],
	[Employee_ID],
	[DaysRemain],
	[DaysPayment],
	[TotalDays],
	[InsertBy],
	[InsertDate],
	[UpdateBy],
	[updateDate]
) VALUES (
	@Year,
	@Employee_ID,
	@DaysRemain,
	@DaysPayment,
	@TotalDays,
	@InsertBy,
	@InsertDate,
	@UpdateBy,
	@updateDate
)

--endregion





GO
