

--region [dbo].[usp_DeleteSetUp]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Admin using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteSetUp]
-- Date Generated: 19 June 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteSetUp]
	@ID nvarchar(255)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[SetUp]
WHERE
	[ID] = @ID

--endregion






GO
