'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("HRSetting"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class HRSetting
    Inherits Global.System.Data.DataSet
    
    Private tableHROption As HROptionDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("HROption")) Is Nothing) Then
                MyBase.Tables.Add(New HROptionDataTable(ds.Tables("HROption")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property HROption() As HROptionDataTable
        Get
            Return Me.tableHROption
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As HRSetting = CType(MyBase.Clone,HRSetting)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("HROption")) Is Nothing) Then
                MyBase.Tables.Add(New HROptionDataTable(ds.Tables("HROption")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableHROption = CType(MyBase.Tables("HROption"),HROptionDataTable)
        If (initTable = true) Then
            If (Not (Me.tableHROption) Is Nothing) Then
                Me.tableHROption.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "HRSetting"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/HRSetting.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableHROption = New HROptionDataTable
        MyBase.Tables.Add(Me.tableHROption)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeHROption() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As HRSetting = New HRSetting
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub HROptionRowChangeEventHandler(ByVal sender As Object, ByVal e As HROptionRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class HROptionDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnOptionID As Global.System.Data.DataColumn
        
        Private columnRoundTimeType As Global.System.Data.DataColumn
        
        Private columnRoundType As Global.System.Data.DataColumn
        
        Private columnFilterMinutes As Global.System.Data.DataColumn
        
        Private columnNightTimeFrom As Global.System.Data.DataColumn
        
        Private columnNightTimeTo As Global.System.Data.DataColumn
        
        Private columnOvertimeSalaryRate As Global.System.Data.DataColumn
        
        Private columnNighttimeSalaryRate As Global.System.Data.DataColumn
        
        Private columnSundaySalaryRate As Global.System.Data.DataColumn
        
        Private columnHolidaySalaryRate As Global.System.Data.DataColumn
        
        Private columnAcceptWorkingEarlyTime As Global.System.Data.DataColumn
        
        Private columnMinimumSalaryBasic As Global.System.Data.DataColumn
        
        Private columnUnionFee As Global.System.Data.DataColumn
        
        Private columnProbationSalaryPercent As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "HROption"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property OptionIDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOptionID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property RoundTimeTypeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRoundTimeType
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property RoundTypeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRoundType
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property FilterMinutesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFilterMinutes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NightTimeFromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNightTimeFrom
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NightTimeToColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNightTimeTo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property OvertimeSalaryRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOvertimeSalaryRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NighttimeSalaryRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNighttimeSalaryRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SundaySalaryRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSundaySalaryRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property HolidaySalaryRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHolidaySalaryRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property AcceptWorkingEarlyTimeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAcceptWorkingEarlyTime
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MinimumSalaryBasicColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMinimumSalaryBasic
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UnionFeeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUnionFee
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ProbationSalaryPercentColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnProbationSalaryPercent
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As HROptionRow
            Get
                Return CType(Me.Rows(index),HROptionRow)
            End Get
        End Property
        
        Public Event HROptionRowChanging As HROptionRowChangeEventHandler
        
        Public Event HROptionRowChanged As HROptionRowChangeEventHandler
        
        Public Event HROptionRowDeleting As HROptionRowChangeEventHandler
        
        Public Event HROptionRowDeleted As HROptionRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddHROptionRow(ByVal row As HROptionRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddHROptionRow(ByVal OptionID As Integer, ByVal RoundTimeType As Integer, ByVal RoundType As Integer, ByVal FilterMinutes As Integer, ByVal NightTimeFrom As Date, ByVal NightTimeTo As Date, ByVal OvertimeSalaryRate As Integer, ByVal NighttimeSalaryRate As Integer, ByVal SundaySalaryRate As Integer, ByVal HolidaySalaryRate As Integer, ByVal AcceptWorkingEarlyTime As Boolean, ByVal MinimumSalaryBasic As Double, ByVal UnionFee As Double, ByVal ProbationSalaryPercent As Integer) As HROptionRow
            Dim rowHROptionRow As HROptionRow = CType(Me.NewRow,HROptionRow)
            Dim columnValuesArray() As Object = New Object() {OptionID, RoundTimeType, RoundType, FilterMinutes, NightTimeFrom, NightTimeTo, OvertimeSalaryRate, NighttimeSalaryRate, SundaySalaryRate, HolidaySalaryRate, AcceptWorkingEarlyTime, MinimumSalaryBasic, UnionFee, ProbationSalaryPercent}
            rowHROptionRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowHROptionRow)
            Return rowHROptionRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByOptionID(ByVal OptionID As Integer) As HROptionRow
            Return CType(Me.Rows.Find(New Object() {OptionID}),HROptionRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As HROptionDataTable = CType(MyBase.Clone,HROptionDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New HROptionDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnOptionID = MyBase.Columns("OptionID")
            Me.columnRoundTimeType = MyBase.Columns("RoundTimeType")
            Me.columnRoundType = MyBase.Columns("RoundType")
            Me.columnFilterMinutes = MyBase.Columns("FilterMinutes")
            Me.columnNightTimeFrom = MyBase.Columns("NightTimeFrom")
            Me.columnNightTimeTo = MyBase.Columns("NightTimeTo")
            Me.columnOvertimeSalaryRate = MyBase.Columns("OvertimeSalaryRate")
            Me.columnNighttimeSalaryRate = MyBase.Columns("NighttimeSalaryRate")
            Me.columnSundaySalaryRate = MyBase.Columns("SundaySalaryRate")
            Me.columnHolidaySalaryRate = MyBase.Columns("HolidaySalaryRate")
            Me.columnAcceptWorkingEarlyTime = MyBase.Columns("AcceptWorkingEarlyTime")
            Me.columnMinimumSalaryBasic = MyBase.Columns("MinimumSalaryBasic")
            Me.columnUnionFee = MyBase.Columns("UnionFee")
            Me.columnProbationSalaryPercent = MyBase.Columns("ProbationSalaryPercent")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnOptionID = New Global.System.Data.DataColumn("OptionID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOptionID)
            Me.columnRoundTimeType = New Global.System.Data.DataColumn("RoundTimeType", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRoundTimeType)
            Me.columnRoundType = New Global.System.Data.DataColumn("RoundType", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRoundType)
            Me.columnFilterMinutes = New Global.System.Data.DataColumn("FilterMinutes", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFilterMinutes)
            Me.columnNightTimeFrom = New Global.System.Data.DataColumn("NightTimeFrom", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNightTimeFrom)
            Me.columnNightTimeTo = New Global.System.Data.DataColumn("NightTimeTo", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNightTimeTo)
            Me.columnOvertimeSalaryRate = New Global.System.Data.DataColumn("OvertimeSalaryRate", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOvertimeSalaryRate)
            Me.columnNighttimeSalaryRate = New Global.System.Data.DataColumn("NighttimeSalaryRate", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNighttimeSalaryRate)
            Me.columnSundaySalaryRate = New Global.System.Data.DataColumn("SundaySalaryRate", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSundaySalaryRate)
            Me.columnHolidaySalaryRate = New Global.System.Data.DataColumn("HolidaySalaryRate", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHolidaySalaryRate)
            Me.columnAcceptWorkingEarlyTime = New Global.System.Data.DataColumn("AcceptWorkingEarlyTime", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAcceptWorkingEarlyTime)
            Me.columnMinimumSalaryBasic = New Global.System.Data.DataColumn("MinimumSalaryBasic", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMinimumSalaryBasic)
            Me.columnUnionFee = New Global.System.Data.DataColumn("UnionFee", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUnionFee)
            Me.columnProbationSalaryPercent = New Global.System.Data.DataColumn("ProbationSalaryPercent", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnProbationSalaryPercent)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("HRSettingKey1", New Global.System.Data.DataColumn() {Me.columnOptionID}, true))
            Me.columnOptionID.AllowDBNull = false
            Me.columnOptionID.Unique = true
            Me.columnRoundTimeType.AllowDBNull = false
            Me.columnRoundType.AllowDBNull = false
            Me.columnFilterMinutes.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewHROptionRow() As HROptionRow
            Return CType(Me.NewRow,HROptionRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New HROptionRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(HROptionRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.HROptionRowChangedEvent) Is Nothing) Then
                RaiseEvent HROptionRowChanged(Me, New HROptionRowChangeEvent(CType(e.Row,HROptionRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.HROptionRowChangingEvent) Is Nothing) Then
                RaiseEvent HROptionRowChanging(Me, New HROptionRowChangeEvent(CType(e.Row,HROptionRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.HROptionRowDeletedEvent) Is Nothing) Then
                RaiseEvent HROptionRowDeleted(Me, New HROptionRowChangeEvent(CType(e.Row,HROptionRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.HROptionRowDeletingEvent) Is Nothing) Then
                RaiseEvent HROptionRowDeleting(Me, New HROptionRowChangeEvent(CType(e.Row,HROptionRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveHROptionRow(ByVal row As HROptionRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As HRSetting = New HRSetting
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "HROptionDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class HROptionRow
        Inherits Global.System.Data.DataRow
        
        Private tableHROption As HROptionDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableHROption = CType(Me.Table,HROptionDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OptionID() As Integer
            Get
                Return CType(Me(Me.tableHROption.OptionIDColumn),Integer)
            End Get
            Set
                Me(Me.tableHROption.OptionIDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property RoundTimeType() As Integer
            Get
                Return CType(Me(Me.tableHROption.RoundTimeTypeColumn),Integer)
            End Get
            Set
                Me(Me.tableHROption.RoundTimeTypeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property RoundType() As Integer
            Get
                Return CType(Me(Me.tableHROption.RoundTypeColumn),Integer)
            End Get
            Set
                Me(Me.tableHROption.RoundTypeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FilterMinutes() As Integer
            Get
                Return CType(Me(Me.tableHROption.FilterMinutesColumn),Integer)
            End Get
            Set
                Me(Me.tableHROption.FilterMinutesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NightTimeFrom() As Date
            Get
                Try 
                    Return CType(Me(Me.tableHROption.NightTimeFromColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NightTimeFrom' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.NightTimeFromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NightTimeTo() As Date
            Get
                Try 
                    Return CType(Me(Me.tableHROption.NightTimeToColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NightTimeTo' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.NightTimeToColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OvertimeSalaryRate() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableHROption.OvertimeSalaryRateColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OvertimeSalaryRate' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.OvertimeSalaryRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NighttimeSalaryRate() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableHROption.NighttimeSalaryRateColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NighttimeSalaryRate' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.NighttimeSalaryRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SundaySalaryRate() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableHROption.SundaySalaryRateColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SundaySalaryRate' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.SundaySalaryRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property HolidaySalaryRate() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableHROption.HolidaySalaryRateColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HolidaySalaryRate' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.HolidaySalaryRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AcceptWorkingEarlyTime() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableHROption.AcceptWorkingEarlyTimeColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'AcceptWorkingEarlyTime' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.AcceptWorkingEarlyTimeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MinimumSalaryBasic() As Double
            Get
                Try 
                    Return CType(Me(Me.tableHROption.MinimumSalaryBasicColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MinimumSalaryBasic' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.MinimumSalaryBasicColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UnionFee() As Double
            Get
                Try 
                    Return CType(Me(Me.tableHROption.UnionFeeColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UnionFee' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.UnionFeeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ProbationSalaryPercent() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableHROption.ProbationSalaryPercentColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ProbationSalaryPercent' in table 'HROption' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHROption.ProbationSalaryPercentColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNightTimeFromNull() As Boolean
            Return Me.IsNull(Me.tableHROption.NightTimeFromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNightTimeFromNull()
            Me(Me.tableHROption.NightTimeFromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNightTimeToNull() As Boolean
            Return Me.IsNull(Me.tableHROption.NightTimeToColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNightTimeToNull()
            Me(Me.tableHROption.NightTimeToColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsOvertimeSalaryRateNull() As Boolean
            Return Me.IsNull(Me.tableHROption.OvertimeSalaryRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetOvertimeSalaryRateNull()
            Me(Me.tableHROption.OvertimeSalaryRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNighttimeSalaryRateNull() As Boolean
            Return Me.IsNull(Me.tableHROption.NighttimeSalaryRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNighttimeSalaryRateNull()
            Me(Me.tableHROption.NighttimeSalaryRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSundaySalaryRateNull() As Boolean
            Return Me.IsNull(Me.tableHROption.SundaySalaryRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSundaySalaryRateNull()
            Me(Me.tableHROption.SundaySalaryRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsHolidaySalaryRateNull() As Boolean
            Return Me.IsNull(Me.tableHROption.HolidaySalaryRateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetHolidaySalaryRateNull()
            Me(Me.tableHROption.HolidaySalaryRateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAcceptWorkingEarlyTimeNull() As Boolean
            Return Me.IsNull(Me.tableHROption.AcceptWorkingEarlyTimeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAcceptWorkingEarlyTimeNull()
            Me(Me.tableHROption.AcceptWorkingEarlyTimeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMinimumSalaryBasicNull() As Boolean
            Return Me.IsNull(Me.tableHROption.MinimumSalaryBasicColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMinimumSalaryBasicNull()
            Me(Me.tableHROption.MinimumSalaryBasicColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUnionFeeNull() As Boolean
            Return Me.IsNull(Me.tableHROption.UnionFeeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUnionFeeNull()
            Me(Me.tableHROption.UnionFeeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsProbationSalaryPercentNull() As Boolean
            Return Me.IsNull(Me.tableHROption.ProbationSalaryPercentColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetProbationSalaryPercentNull()
            Me(Me.tableHROption.ProbationSalaryPercentColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class HROptionRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As HROptionRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As HROptionRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As HROptionRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
