CREATE TABLE [dbo].[HR_Report] (
    [ID] INT IDENTITY(1,1) NOT NULL,
    [ReportFather] VARCHAR(50) NULL,
    [OrderBy] INT NULL,
    [ReportCode] VARCHAR(50) NOT NULL,
    [TabKey] NVARCHAR(50) NULL,
    [NameVN] NVARCHAR(256) NULL,
    [NameEN] NVARCHAR(256) NULL,
    [NameKR] NVARCHAR(256) NULL,
    [TemplateFile] VARCHAR(256) NULL,
    [NameOfFuntion] VARCHAR(256) NULL,
    [NameOfTable] VARCHAR(256) NULL,
    [NameOfStore] VARCHAR(256) NULL,
    [ParameterForm] NVARCHAR(50) NULL,
    [ParameterFormNotShow] BIT NULL,
    [Parameter] VARCHAR(256) NULL,
    [GroupBy] VARCHAR(50) NULL,
    [ManySheet] BIT NULL,
    [ViewOnGrid] BIT NULL,
    [ExportExcel] BIT NULL,
    [SaveData] BIT NULL,
    [PrintView] BIT NULL,
    [PrinViewDocument] BIT NULL,
    [PrintViewDocument_FieldKey] VARCHAR(50) NULL,
    [PrinViewDocument_Excel] BIT NULL,
    [ExportDocumentFile] BIT NULL,
    [GetTemplateFile] BIT NULL,
    [InputTemplateFile] BIT NULL,
    [ExecStore] BIT NULL,
    [ExecSubOrFunctionOfVB] BIT NULL,
    [GridName] VARCHAR(50) NULL,
    [BorderLine] INT NULL,
    [PrimaryConfigLine] INT NULL,
    [SaveConfigLine] INT NULL,
    [ConfigLine] INT NULL,
    [HeaderLine] INT NULL,
    [WriteLine] INT NULL,
    [SelectField] NVARCHAR(MAX) NULL,
    [ValueInExcelCell] NVARCHAR(126) NULL,
    [Translate] BIT NULL,
    [Remark] NVARCHAR(256) NULL,
    [Filter] VARCHAR(MAX) NULL,
    [LanguageForm] NVARCHAR(50) NULL,
    [InsertDateName] NVARCHAR(50) NULL,
    [UserNameName] NVARCHAR(50) NULL,
    [ControlNameAction] NVARCHAR(50) NULL,
    [InsertDate] DATETIME NULL,
    [UserName] NVARCHAR(50) NULL,
    [NotUsing] BIT NULL,
    [Excel_XoaDenDong] INT NULL,
    [FrozenColumn] INT NULL,
    [NotDeleteConfig] BIT NULL
);

ALTER TABLE [dbo].[HR_Report] ADD CONSTRAINT [PK_HR_Report] PRIMARY KEY ([ReportCode] ASC);
