CREATE TABLE [dbo].[SmartBooks_Employee] (
    [Employee_ID] NVARCHAR(255) NOT NULL,
    [Employee_Firstname] NVARCHAR(255) NOT NULL,
    [Employee_LastName] NVARCHAR(255) NULL,
    [BirthDate] DATETIME NOT NULL,
    [BirthPlace] NVARCHAR(255) NULL,
    [Sex] NVARCHAR(255) NOT NULL,
    [MaritalStatus] NVARCHAR(255) NULL,
    [Nationality] NVARCHAR(255) NULL,
    [Nation] NVARCHAR(50) NULL,
    [ID_number] NVARCHAR(255) NOT NULL,
    [ID_date] DATETIME NULL,
    [NgayHetHanCCCD] DATETIME NULL,
    [ID_place] NVARCHAR(255) NULL,
    [Address_Temporary] NVARCHAR(255) NULL,
    [Address_Permanent] NVARCHAR(255) NULL,
    [NativePlace] NVARCHAR(255) NULL,
    [Employee_Status] NVARCHAR(255) NULL,
    [StartedDate] DATETIME NULL,
    [ComStartedDate] DATETIME NULL,
    [Factory_ID] NVARCHAR(50) NULL,
    [DepartmentCode] NVARCHAR(50) NULL,
    [SectionCode] NVARCHAR(100) NULL,
    [TeamCode] NVARCHAR(50) NULL,
    [Position_ID] NVARCHAR(50) NULL,
    [PositionCategory_ID] NVARCHAR(50) NULL,
    [ChucDanh] NVARCHAR(50) NULL,
    [JobCode] NVARCHAR(50) NULL,
    [CongViecPhaiLam] NVARCHAR(MAX) NULL,
    [Card_No] NVARCHAR(50) NULL,
    [Card_Code] NVARCHAR(50) NULL,
    [TypeOfHiring] NVARCHAR(50) NULL,
    [BankName] NVARCHAR(255) NULL,
    [BankCode] NVARCHAR(50) NULL,
    [DebitAccount] NVARCHAR(50) NULL,
    [Qualification] NVARCHAR(255) NULL,
    [OfficialDate] DATETIME NULL,
    [Graduated] NVARCHAR(50) NULL,
    [GraduatedFrom] NVARCHAR(255) NULL,
    [TernimationDate] DATETIME NULL,
    [Tel] NVARCHAR(255) NULL,
    [Email] NVARCHAR(50) NULL,
    [MaSoThue] NVARCHAR(50) NULL,
    [SoNgayPhepNam] FLOAT NULL,
    [ContractFlow] NVARCHAR(50) NULL,
    [TonGiao] NVARCHAR(100) NULL,
    [NguoiLienHeGap] NVARCHAR(MAX) NULL,
    [Height] FLOAT NULL,
    [Weight] FLOAT NULL,
    [Hospital] NVARCHAR(255) NULL,
    [HealthCheckFee] FLOAT NULL,
    [Remark] NVARCHAR(MAX) NULL,
    [UserName] NVARCHAR(50) NULL,
    [InsertDate] DATETIME NULL,
    [Picture] IMAGE NULL,
    [RFID] NVARCHAR(50) NULL,
    [BirthDateFormat] VARCHAR(10) NULL,
    [TenChuHo] NVARCHAR(50) NULL,
    [QuanHeVoiChuHo] NVARCHAR(50) NULL,
    [isThuViec85PhanTram] BIT NULL,
    [NgayTGCongDoan] DATETIME NULL,
    [EndOfSeasonWorker] DATETIME NULL,
    [IsSeasonWorker] BIT NULL,
    [isManager] BIT NULL,
    [Camket] BIT NULL,
    [NguoiGT] NVARCHAR(100) NULL,
    [Accountcode1] NVARCHAR(50) NULL,
    [Accountcode2] NVARCHAR(50) NULL,
    [Accountcode3] NVARCHAR(50) NULL,
    [PicCam] IMAGE NULL,
    [CCCDCu] NVARCHAR(50) NULL,
    [CCCDCu_Date] DATETIME NULL,
    [CCCDCu_Place] NVARCHAR(500) NULL,
    [isTanTat] BIT NULL,
    [TanTat] NVARCHAR(100) NULL,
    [ResonTerminated] NVARCHAR(200) NULL,
    [SoNhaThonXom] NVARCHAR(100) NULL,
    [PhuongXa] NVARCHAR(100) NULL,
    [QuanHuyen] NVARCHAR(100) NULL,
    [TinhThanhPho] NVARCHAR(100) NULL
);

ALTER TABLE [dbo].[SmartBooks_Employee] ADD CONSTRAINT [PK_SmartBooks_Employee] PRIMARY KEY ([Employee_ID] ASC);
